### ISSUE TITLE
It must be a good idea to support Discord robot!

### ISSUE THREAD

**Issue by misaka19465** [cyb233/mimikkoAutoSignIn#10]
签到以后发到Discord服务器，岂不美哉？

**Comment by cyb233** [comment]
确实美哉，但看了眼全英文的文档，我觉得我要等下个月下船才有耐心做(这个月先补实习报告去)

**Comment by cyb233** [comment]
看了眼别人写的，发现不难，就顺便写好了(官方文档完全没看懂，算了算了)
![Screenshot_2021_0418_113651](https://user-images.githubusercontent.com/39186981/115134465-88498900-a03a-11eb-918c-1b07bded90a5.png)

**Comment by cyb233** [comment]
频道→整合→创建webhook→复制webhook

然后新建名为`discord`的secret，把webhook粘贴进去即可
