### ISSUE TITLE
Welcome to misakaNet!

### ISSUE THREAD

**Issue by misaka19465** [cyb233/mimikkoAutoSignIn#21]
刚刚写好一个消息推送软件, OlddoctorDevTeam/misakaNet
还没来得及写文档，
接入方法：
要求输入服务器IP(misaka20001position)和misakaKey(用来定位用户)
把misakaKey传入header:
e.g.  misaka-key: test
发送一个POST, body就是要推送的消息

**Comment by cyb233** [comment]
意思是header={misaka-key: test}，body=post_data，然后发送到自己的服务器地址？

**Comment by misaka19465** [comment]
对

**Comment by misaka19465** [comment]
key不全是test, 是用户自己添的

**Comment by misaka19465** [comment]
所以为什么平常都天天更新今天没反应

**Comment by cyb233** [comment]
开航了，干活忙加离岸有些远不想找信号


---Original---
From: &quot;Misaka ***@***.***&gt;
Date: Thu, Apr 22, 2021 22:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cyb233/mimikkoAutoSignIn] Welcome to misakaNet! (#21)




 
所以为什么平常都天天更新今天没反应
 
&mdash;
