### ISSUE TITLE
好感度上限

### ISSUE THREAD

**Issue by misaka19465** [cyb233/mimikkoAutoSignIn#42]
zfjdhj那边弄了个到上限换下一个助手的功能  这边有吗？也整一个？

**Comment by cyb233** [comment]
嗯，这个可以有，不过最近比较懒，过两天再看看

**Comment by cyb233** [comment]
https://github.com/cyb233/mimikkoAutoSignIn/commit/83c1aff7a75aaf725794840948ab750f4702bb01
改好了，懒得测试，等有空了看看有没有bug，确认完我再pr
加了个参数-v，用来指定最大好感度，不设置时默认136000（普通助手4升5，超级助手2升3）
