### ISSUE TITLE
关于补签

### ISSUE THREAD

**Issue by misaka19465** [cyb233/mimikkoAutoSignIn#43]
补签上限现在不是30天嘛  设置成30可以用吗  可以的话把文档里面的改掉吧

**Comment by cyb233** [comment]
这个官方也改过了吗？不过对脚本而言30天用处不大，因为一般不会断签
https://github.com/cyb233/mimikkoAutoSignIn/commit/b5b5176a8d345aa0c8d1ef140fc30639866f2813#diff-c1db9ed241d58ece631c6e1cb2f62c4aac2518d23d4ed2b77d6ca534a8828137
