### ISSUE TITLE
AppID 和 Authorization 可以参考 PHP 版脚本

### ISSUE THREAD

**Issue by LiarOnce** [cyb233/mimikkoAutoSignIn#5]
AppID 的话是写死的，两年没换过（提示：apktool）
Authorization 的话可以参考一下这里：[https://github.com/LiarOnceW/mimikkoAutoSign/blob/master/src/Mimikko.php#L36](https://github.com/LiarOnceW/mimikkoAutoSign/blob/master/src/Mimikko.php#L36)
水：这个原来的 PHP 脚本活了两年

**Comment by cyb233** [comment]
好的，看过了，预计明天更新

**Comment by cyb233** [comment]
奇怪，login_data返回{'code': '2', 'msg': '请求地址不存在'}
https://github.com/cyb233/mimikkoAutoSignIn/blob/master/mimikko.py#L145

**Comment by LiarOnce** [comment]
奇怪了，是不是参数有问题，这是可以成功的
![image](https://user-images.githubusercontent.com/11171892/106580972-4f426200-657d-11eb-9685-4a20b162572c.png)
![image](https://user-images.githubusercontent.com/11171892/106581026-5e291480-657d-11eb-9191-ddc720f44840.png)

**Comment by cyb233** [comment]
除了id和password，所有的参数都在68行了
https://github.com/cyb233/mimikkoAutoSignIn/blob/master/mimikko.py#L68

**Comment by cyb233** [comment]
抓包很正常，重发也很正常，写得也跟脚本里一样，但就是搞不明白
![Screenshot_2021_0202_184720](https://user-images.githubusercontent.com/39186981/106589712-48b8e800-6587-11eb-871f-2e7957c684e5.png)

**Comment by LiarOnce** [comment]
找到原因了，你`requests.post`的用法错了。。。。。。。
https://github.com/cyb233/mimikkoAutoSignIn/blob/master/mimikko.py#L83

**Comment by cyb233** [comment]
好，懂了，谢谢，用错方法是我老毛病了，因为没具体学过😂我改一改去

**Comment by cyb233** [comment]
好，懂了，谢谢，用错方法是我老毛病了，因为没具体学过😂我改一改去

**Comment by cyb233** [comment]
updated
https://github.com/cyb233/mimikkoAutoSignIn/commit/711ecec8ece195e5300ffafd8f62cfa50f03f315
