### ISSUE TITLE
Server酱Turbo支持

### ISSUE THREAD

**Issue by MarcusPierce** [cyb233/mimikkoAutoSignIn#6]
Server酱传统版会在近期下线，请更换为Server酱Turbo（用 sctapi.ftqq.com 替换旧版请求链接中的 sc.ftqq.com即可）
如果方便的话请顺便支持一下钉钉群机器人WebHook

**Comment by cyb233** [comment]
查了下server酱官网，没看到sc下线的消息，且sct免费用户日发送量仅5条，所以暂无更新计划，如有使用需要，可fork后更改`mimikko.py`的第`77`行

**Comment by cyb233** [comment]
另外关于钉钉机器人接入，因为没用过，我看了下文档有[3种安全验证方式](https://developers.dingtalk.com/document/app/custom-robot-access#topic-2026027)，哪一种是你们常用的？签名验证官方文档倒是有现成的Python可以抄，如果要支持的话可能要稍晚些，最近没什么空

**Comment by cyb233** [comment]
已添加钉钉机器人推送，使用签名认证方式，因为我没有钉钉机器人，所以请fork新版本后测试

**Comment by cyb233** [comment]
PS，测试完希望给我个回复

**Comment by cyb233** [comment]
PS，测试完希望给我个回复

**Comment by MarcusPierce** [comment]
> 查了下server酱官网，没看到sc下线的消息，且sct免费用户日发送量仅5条，所以暂无更新计划，如有使用需要，可fork后更改`mimikko.py`的第`77`行

http://sc.ftqq.com/9.version
升级说明

**Comment by MarcusPierce** [comment]
> 已添加钉钉机器人推送，使用签名认证方式，因为我没有钉钉，所以希望fork新版本后测试一下
> 
> 钉钉的secret请参考server酱一样保存，名称为DDKEY

同类项目钉钉推送一般会让在项目**secret**里添加两个参数，一个是钉钉机器人的webhook，一个是选择签名验证方式后给的机器人secret
可以参考[https://github.com/y1ndan/genshin-impact-helper](原神签到) 的实现

**Comment by cyb233** [comment]
> > 已添加钉钉机器人推送，使用签名认证方式，因为我没有钉钉，所以希望fork新版本后测试一下
> > 钉钉的secret请参考server酱一样保存，名称为DDKEY
> 
> 同类项目钉钉推送一般会让在项目**secret**里添加两个参数，一个是钉钉机器人的webhook，一个是选择签名验证方式后给的机器人secret
> 可以参考[https://github.com/y1ndan/genshin-impact-helper](%E5%8E%9F%E7%A5%9E%E7%AD%BE%E5%88%B0) 的实现

根据钉钉API文档，webhook的链接格式不是固定的吗？没必要加在secret里吧？

**Comment by MarcusPierce** [comment]
> > > 已添加钉钉机器人推送，使用签名认证方式，因为我没有钉钉，所以希望fork新版本后测试一下
> > > 钉钉的secret请参考server酱一样保存，名称为DDKEY
> > 
> > 
> > 同类项目钉钉推送一般会让在项目**secret**里添加两个参数，一个是钉钉机器人的webhook，一个是选择签名验证方式后给的机器人secret
> > 可以参考[https://github.com/y1ndan/genshin-impact-helper](%E5%8E%9F%E7%A5%9E%E7%AD%BE%E5%88%B0) 的实现
> 
> 根据钉钉API文档，webhook的链接格式不是固定的吗？没必要加在secret里吧？
钉钉webhook的格式类似这样
https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxx
钉钉secret的格式类似这样
SECxxxxxxxxxxxxxxx
如果需要给开启了签名验证的机器人发送消息，需要包含钉钉secret
关键词验证的话就不需要，但是关键词上限10个，限制了使用场景
ip没人用的，还是加签吧

**Comment by cyb233** [comment]
对了你手动运行的那次action钉钉推送成功了吗？

**Comment by cyb233** [comment]
> > 查了下server酱官网，没看到sc下线的消息，且sct免费用户日发送量仅5条，所以暂无更新计划，如有使用需要，可fork后更改`mimikko.py`的第`77`行
> 
> http://sc.ftqq.com/9.version
> 升级说明

这个的话想了下，我直接两个api都各自推送一遍算了，等sc停用再删

**Comment by MarcusPierce** [comment]
> 对了你手动运行的那次action钉钉推送成功了吗？

只有Webhook没有Secret，不会成功

**Comment by cyb233** [comment]
> > 对了你手动运行的那次action钉钉推送成功了吗？
> 
> 只有Webhook没有Secret，不会成功
> 
> 【66-68行】
> 没有SCKEY
> 运行成功，正在推送到钉钉
> <Response [200]>

我写的请求API是：ding_api + 'access_token=' + DDKEY + '&timestamp=' + dtime + '&sign=' + dsign，里面包含了secret和两个签名参数的

**Comment by MarcusPierce** [comment]
> > > 对了你手动运行的那次action钉钉推送成功了吗？
> > 
> > 
> > 只有Webhook没有Secret，不会成功
> > 【66-68行】
> > 没有SCKEY
> > 运行成功，正在推送到钉钉
> > <Response [200]>
> 
> 我写的请求API是：ding_api + 'access_token=' + DDKEY + '&timestamp=' + dtime + '&sign=' + dsign，里面包含了secret和两个签名参数的
> 
> 另外66行是server酱的返回信息

就最好整一个【DDTOKEN】和一个【DDSECRET】，让填在项目Secret里

**Comment by cyb233** [comment]
没搞懂，根据API文档中链接`https://oapi.dingtalk.com/robot/send?access_token=XXXXXX&timestamp=XXX&sign=XXX`，链接中需要的3个参数：`access_token`由用户提供，`timestamp`为时间戳直接获取，`sign`为前两个组合计算出的签名，不需要提供两个secret啊？你要求的两个secret分别是什么？

**Comment by MarcusPierce** [comment]
> 没搞懂，根据API文档中链接`https://oapi.dingtalk.com/robot/send?access_token=XXXXXX&timestamp=XXX&sign=XXX`，链接中需要的3个参数：`access_token`由用户提供，`timestamp`为时间戳直接获取，`sign`为前两个组合计算出的签名，不需要提供两个secret啊？你要求的两个secret分别是什么？
> 
> ![](https://camo.githubusercontent.com/b705689c4e90c5c4e94144a459b49258d255dd8464fbb9fcefbc2bc48906b803/68747470733a2f2f7374617469632d616c6979756e2d646f632e6f73732d616363656c65726174652e616c6979756e63732e636f6d2f6173736574732f696d672f7a682d434e2f343832343139393935312f703133313232342e706e67)
> 文档里的图也没看到其他需要提供的东西

主要是我也不会开发，看看这个吧https://github.com/y1ndan/genshin-impact-helper

**Comment by cyb233** [comment]
懂了，token和secret不是同一个是吧

**Comment by cyb233** [comment]
现在试试看，分别填写参数【DDTOKEN】和【DDSECRET】

**Comment by cyb233** [comment]
看到你在#34运行的报错了，那里忘记改了，已经改了

**Comment by cyb233** [comment]
测试了下，server酱Turbo版密钥目前可以直接在普通版API中使用，故先注释掉新API，直到旧版不能用为止

**Comment by MarcusPierce** [comment]
> 看到你在#34运行的报错了，那里忘记改了，已经改了
> 
> 啊我报错了，等下
> 
> 现在应该好了

dd 'str' object is not callable

**Comment by cyb233** [comment]
漫游流量用到限速了，这个问题可能要下礼拜解决，根据谷歌搜索这问题是应该命名冲突，问题排查是出在 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L391 即函数 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L172-L179 中，但我还不确定具体原因

**Comment by MarcusPierce** [comment]
> 漫游流量用到限速了，这个问题可能要下礼拜解决，根据谷歌搜索这问题是应该命名冲突，问题排查是出在 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L391 即函数 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L172-L179 中，但我还不确定具体原因

要出海了吗 下周见

**Comment by cyb233** [comment]
嗯，明早走，等到时候申请个钉钉机器人看看，申请机器人还没法用手机APP，真麻烦


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月19日(周五) 晚上8:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cyb233/mimikkoAutoSignIn] Server酱Turbo支持 (#6)




  
漫游流量用到限速了，这个问题可能要下礼拜解决，根据谷歌搜索这问题是应该命名冲突，问题排查是出在 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L391 即函数 https://github.com/cyb233/mimikkoAutoSignIn/blob/c27e2e69e301b5da948b7e5e1244b30d2ef87b00/mimikko.py#L172-L179 中，但我还不确定具体原因
  
要出海了吗 下周见
 
&mdash;

**Comment by cyb233** [comment]
发帖问了一下网友，现已修复

**Comment by cyb233** [comment]
给张钉钉推送的截图我看看，我没有机器人但还是挺好奇的，如果有关键信息可以打码

**Comment by cyb233** [comment]
给张钉钉推送的截图我看看，我没有机器人但还是挺好奇的，如果有关键信息可以打码

**Comment by MarcusPierce** [comment]
> 给张钉钉推送的截图我看看，虽然我没有机器人但还是挺好奇的，如果有关键信息可以打码

**钉钉 <Response [200]>**

失败了，没成功
![image](https://user-images.githubusercontent.com/30462393/111875763-67a7f800-89d6-11eb-87c4-d0e1aaacd892.png)
第一条是使用Server酱钉钉机器人通道的转发推送
第二条是使用原生钉钉机器人的推送
不想用Server酱的理由主要也还是免费额度的问题，没有订阅的话所有消息都只有标题，内容需要点击链接跳转

**Comment by cyb233** [comment]
试了下server酱Turbo版的企业微信推送，免费推送数量似乎并不止5条/天，钉钉的话我可能需要自己有空以后申请一下机器人尝试了

**Comment by cyb233** [comment]
预计现在OK了，再试试吧，如果还不行我就Reopen了

**Comment by MarcusPierce** [comment]
> 试了下server酱Turbo版的企业微信推送，免费推送数量似乎并不止5条/天，钉钉的话我可能需要自己有空以后申请一下机器人尝试了

对，vip试用期间无限制，试用期过后超过限额的仍然会推送但是不会显示内容，需要点击外链跳转到server酱网站查看内容

**Comment by cyb233** [comment]
现在如何？成功了吗？

**Comment by MarcusPierce** [comment]
> 现在如何？成功了吗？如果仍然失败，修改
> 
> https://github.com/cyb233/mimikkoAutoSignIn/blob/af0a269943a5a388130123df71d8264c22b33e66/mimikko.py#L184
> 
> 中`post_data`为`post_data.text`可以看返回的详细信息

改完就Process completed with exit code 1.了

**Comment by cyb233** [comment]
不要拿旧代码覆盖新代码，参数会报错的

**Comment by MarcusPierce** [comment]
> 不要拿旧代码覆盖新代码，参数会报错的
> 
> https://github.com/MarcusPierce/mimikkoAutoSignIn/commit/b7e9db7ab7da4aaea5071f99ab2512386a5be376
> 
> 你看看你改的，我说只要加个`.text`，你改动了多少处？

建议注明DDTOKEN的值只填access_token=后的内容
因为钉钉创建机器人时自动复制的是包含所有内容的完整链接
现在推送成功了，但是消息样式有问题，PC端和iOS端都是
![image](https://user-images.githubusercontent.com/30462393/112792365-e3203e00-9095-11eb-8bfb-71f017cc11cd.jpeg)

**Comment by cyb233** [comment]
说明内容我待会儿会改一下
样式问题我无法确定原因，我使用的是markdown格式，与server酱推送排版以及action推送是一样的，即与下面一致
https://github.com/MarcusPierce/mimikkoAutoSignIn/runs/2215819890?check_suite_focus=true#step:4:67

**Comment by MarcusPierce** [comment]
> 说明内容我待会儿会改一下
> 
> 样式问题我无法确定原因，我使用的是markdown格式，与server酱推送排版以及action推送是一样的，即与下面一致
> 
> https://github.com/MarcusPierce/mimikkoAutoSignIn/runs/2215819890?check_suite_focus=true#step:4:67

很奇怪，甚至不能显示完整的消息，但是小窗消息预览能看出是什么

**Comment by cyb233** [comment]
显示问题我去问问客服，token问题我晚些看看直接在代码上改

**Comment by cyb233** [comment]
在吗？现在fork一下最新版本看看能不能正常显示

**Comment by cyb233** [comment]
现已支持企业微信API直接推送，就差你这个钉钉还不知道有没有问题了
![Screenshot_20210329_211357](https://user-images.githubusercontent.com/39186981/112850036-d9b5c680-90d3-11eb-9f69-b76496abc1fe.jpg)

**Comment by MarcusPierce** [comment]
> 现已支持企业微信API直接推送，就差你这个钉钉还不知道有没有问题了
> 
> ![Screenshot_20210329_211357](https://user-images.githubusercontent.com/39186981/112850036-d9b5c680-90d3-11eb-9f69-b76496abc1fe.jpg)
> 
> 

重新fork了一遍

钉钉 errcode: 40035

**Comment by cyb233** [comment]
改了一下推送报错返回的机制，你看看具体怎么返回的

**Comment by cyb233** [comment]
已解决
![Screenshot_2021_0403_195345](https://user-images.githubusercontent.com/39186981/113479073-faf12b00-94b6-11eb-8643-3197883efc4b.png)

**Comment by MarcusPierce** [comment]
麻了，又Error: Process completed with exit code 1.

**Comment by cyb233** [comment]
> 麻了，又Error: Process completed with exit code 1.

我看了你的action，报错代码310000是：
>// 签名不匹配
>{
>  "errcode":310000,
>  "errmsg":"sign not match"
>}
这原因我就不清楚了，因为我这里是好着的……

**Comment by cyb233** [comment]
> 麻了，又Error: Process completed with exit code 1.

你重新拷贝一下secret看看
